# GitHub Sponsors and donation links.
# Replace placeholder handles once funding channels are live.

github: MarcusMedina
patreon: marcusmedina
ko_fi: marcusmedina
custom:
  - https://marcusmedina.pro/support
