name: Sign & Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: [self-hosted, windows, code-sign]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore packages
        run: nuget restore TopWinPrio.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Release
        run: msbuild TopWinPrio.sln /t:Build /p:Configuration=Release

      - name: Sign executable with Certum SimplySign
        shell: pwsh
        run: |
          $exePath = "TopWinPrio.CS\bin\Release\TopWinPrio.exe"
          $signtoolPath1 = "C:\Program Files (x86)\Certum\SimplySign Desktop\signtool.exe"
          $signtoolPath2 = "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool.exe"
          $timestampUrl = "http://timestamp.certum.pl"

          if (-not (Test-Path $exePath)) {
              Write-Error "❌ Executable not found: $exePath"
              exit 1
          }

          if (Test-Path $signtoolPath1) {
              $signtool = $signtoolPath1
          } elseif (Test-Path $signtoolPath2) {
              $signtool = $signtoolPath2
          } else {
              Write-Error "❌ signtool.exe not found."
              exit 1
          }

          Write-Host "🔐 Signing $exePath using SimplySign..."
          & $signtool sign `
              /tr $timestampUrl `
              /td SHA256 `
              /fd SHA256 `
              /n "Open Source Developer, Marcus Ackre Medina" `
              "$exePath"

          if ($LASTEXITCODE -eq 0) {
              Write-Host "✅ Signing successful."
          } else {
              Write-Error "⚠️ signtool exited with code $LASTEXITCODE."
              exit 1
          }

      - name: Prepare release artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path artifacts | Out-Null
          Copy-Item "TopWinPrio.CS/bin/Release/TopWinPrio.exe" "artifacts/TopWinPrio.exe" -Force
          Compress-Archive -Path "TopWinPrio.CS/bin/Release/*" -DestinationPath "artifacts/TopWinPrio-release.zip" -Force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
